export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const TOGGLE_EXCHANGE = 'TOGGLE_EXCHANGE';
export const SET_EXCHANGE_AMOUNT = 'SET_EXCHANGE_AMOUNT';
export const GET_WALLETS = 'GET_WALLETS';
export const UPDATE_WALLETS = 'UPDATE_WALLETS';
